#!/usr/bin/env bash
# Rebuild the search_results/CLAUDE.md index from all stored result files
# Usage: update-index.sh <results-dir>
# This is the ONLY way to update the index. Never edit CLAUDE.md by hand.

set -euo pipefail

if [ $# -eq 0 ]; then
  echo "Usage: update-index.sh <results-dir>" >&2
  exit 1
fi

RESULTS_DIR="$1"
INDEX_FILE="$RESULTS_DIR/CLAUDE.md"

mkdir -p "$RESULTS_DIR"

# Collect all result files (newest first)
files=$(find "$RESULTS_DIR" -name '*.md' ! -name 'CLAUDE.md' -type f | sort -r)

# Build the index
cat > "$INDEX_FILE" << 'HEADER'
# Search Results Index

> Auto-generated index of stored search results. **Do not edit this file manually.**
> Regenerate with: `bash ~/.claude/skills/search/scripts/update-index.sh <results-dir>`

HEADER

if [ -z "$files" ]; then
  echo "_No search results stored yet._" >> "$INDEX_FILE"
  echo "Index updated: 0 entries."
  exit 0
fi

count=0
current_month=""

while IFS= read -r file; do
  slug=$(basename "$file" .md)

  # Parse frontmatter
  query=""
  mode=""
  date=""
  time_span=""

  in_frontmatter=false
  while IFS= read -r line; do
    if [ "$line" = "---" ]; then
      if $in_frontmatter; then
        break
      else
        in_frontmatter=true
        continue
      fi
    fi
    if $in_frontmatter; then
      case "$line" in
        query:*) query="${line#query: }" ;;
        mode:*) mode="${line#mode: }" ;;
        date:*) date="${line#date: }" ;;
        time_span:*) time_span="${line#time_span: }" ;;
      esac
    fi
  done < "$file"

  # Group by month
  month=$(echo "$date" | cut -c1-7)  # YYYY-MM
  if [ "$month" != "$current_month" ]; then
    current_month="$month"
    # Format as "February 2026"
    if command -v date &>/dev/null; then
      month_label=$(date -d "${month}-01" +"%B %Y" 2>/dev/null || echo "$month")
    else
      month_label="$month"
    fi
    echo "" >> "$INDEX_FILE"
    echo "## $month_label" >> "$INDEX_FILE"
    echo "" >> "$INDEX_FILE"
    echo "| Date | Mode | Query | File |" >> "$INDEX_FILE"
    echo "|------|------|-------|------|" >> "$INDEX_FILE"
  fi

  echo "| $date | $mode | $query | [$slug]($slug.md) |" >> "$INDEX_FILE"
  count=$((count + 1))
done <<< "$files"

echo "" >> "$INDEX_FILE"
echo "---" >> "$INDEX_FILE"
echo "_${count} result(s) indexed._" >> "$INDEX_FILE"

echo "Index updated: $count entries."
